Deleted so we have 3 scenes and adjusted the level select buttons so …
gwenvis/pvb-programming pull request #15
Opened 2020-04-22 16:01 UTC by FloydMa1

…they have an image instead of a text

2020-04-22 17:52 UTC, stepperman commented
'' is an incorrect path for a scene file. BuildPlayer expects paths relative to the project folder.

2020-04-22 18:04 UTC, gwenvis requested changes

2020-04-22 18:04 UTC, stepperman commented on Assets/Scripts/UI/Buttons/LevelButtonLoader.cs
> +                button.transform.GetChild(0).transform.GetChild(0).GetComponent<Image>().sprite = levelsData.Levels[i].LevelImage;
`GetComponentInChildren()` pls.

2020-05-06 10:19 UTC, gwenvis approved these changes

2020-05-06 10:20 UTC, merged