Added lives
gwenvis/pvb-programming pull request #7
Opened 2020-04-21 09:30 UTC by joppevanbasten

added lives, The lives script has to be added to the Canvas.

2020-04-21 09:34 UTC, gwenvis requested changes

2020-04-21 09:34 UTC, stepperman commented on Assets/Scripts/Health/Lives.cs
> +		RectTransform canvas;
access modifier pls.

2020-04-21 09:34 UTC, stepperman commented on Assets/Scripts/Health/Lives.cs
> +		}
niet heel bijzonder, maar maak hier een Property van. Is wat netter.

2020-04-21 09:34 UTC, stepperman commented on Assets/Scripts/Health/Lives.cs
> +		[SerializeField] private int size = 15;
wat als ik een size wil van 13.5 !!!!

2020-04-21 09:53 UTC, gwenvis requested changes

2020-04-21 09:53 UTC, stepperman commented on Assets/Scripts/Health/Lives.cs
> +		}
Properties moeten altijd met hoofdletter.

Dit kan trouwens ook korter (hoeft niet hoor, als je dit meer leesbaar vindt)
`public int CurrentLives => hearts.Count`

2020-04-21 09:53 UTC, stepperman commented on Assets/Scripts/Health/Lives.cs
> +				g.transform.parent = transform;
noem een object geen g, geef het een leesbare naam zodat het makkelijker is om te begrijpen wat voor object het is.

2020-04-21 09:53 UTC, stepperman commented on Assets/Scripts/Health/Lives.cs
> +				hearts.RemoveAt(hearts.Count - 1);
voeg misschien een event toe die andere classes kunnen gebruiken als health nul of minder is?

2020-04-21 17:43 UTC, gwenvis reviewed
paar dingen nog

2020-04-21 17:43 UTC, stepperman commented on Assets/Scripts/Health/Lives.cs
> +				CurrentLives--;
Gooi dit buiten de if statement. De functie impliceert dat levens verloren worden, maar dit gebeurt alleen maar als het boven de nul is. Het is ook niet erg als er minder dan 0 levens zijn dus daar is een check voor.

2020-04-21 17:43 UTC, stepperman commented on Assets/Scripts/Health/LivesUI.cs
> +		Lives lives = new Lives();
access modifier

2020-04-21 17:43 UTC, stepperman commented on Assets/Scripts/Health/LivesUI.cs
> +			lives.LifeLostEvent += OnLiveLostEvent;
Je unsubscribed dit nooit. Unsubscribe het in een `OnDestroy()` functie.

2020-04-22 09:00 UTC, joppevanbasten commented on Assets/Scripts/Health/Lives.cs
> +		}
fixed

2020-04-22 09:45 UTC, gwenvis approved these changes

2020-04-22 09:45 UTC, merged